spring.application.name=demo

mybatis.mapper-locations=classpath:mapper/**/*.xml

spring.h2.console.enabled=true

#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=10
#
#logging.level.com.example.demo.mapper.MemberMapper=TRACE